import Head from 'next/head'
import Script from 'next/script'
import Link from 'next/link'
import Form from '../components/Form'

export default function Home() {

  const alunoForm = {
    nome: "",
    cpf: "",
    sexo: "",
    email: "",

  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav className="navbar navbar-expand-lg bg-light">
    <div className="container-fluid">
      <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span className="navbar-toggler-icon"></span>
      </button>
      <div className="collapse navbar-collapse justify-content-center text-center" id="navbarNav">
        <ul className="navbar-nav">
          <li className="nav-item">
            <Link href="/alunos"><a className="nav-link">Alunos</a></Link>
          </li>
          <li className="nav-item">
            <Link href="/estatisticas"><a className="nav-link">Estatísticas</a></Link>
          </li>
          <li className="nav-item">
            <Link href="/localizacoes"><a className="nav-link">Localizações</a></Link>
          </li>
          <li className="nav-item">
          <a className="nav-link" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom" href=''>Cadastrar</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div className="offcanvas offcanvas-bottom h-75" tabIndex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
  <div className="offcanvas-header">
    <h5 className="offcanvas-title" id="offcanvasBottomLabel">Cadastrar Aluno</h5>
    <button type="button" className="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div className="offcanvas-body small">
    <Form alunoForm={alunoForm} />
  </div>
</div>
    
    <main>
      <div className="container-fluid mainer">
      </div>
    </main>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></Script>
    </div>
  )
}
